apiVersion: v1
kind: ResourceQuota
metadata:
  name: ns-quota
  namespace: eks-example
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 1Gi
    requests.nvidia.com/gpu: 4
    
    